#All privilege-escalation playbook
- import_playbook: T1015.yaml
# AVAILABE TAGS:  OSK,SETHC,UTILMAN,MAGNIFY,NARRATOR,DISPLAYSWITCH,ATBROKER
  ignore_errors: yes
# - import_playbook: T1088.yaml
#  ignore_errors: yes
#- import_playbook: T1103.yaml
#  ignore_errors: yes
- import_playbook: T1134.yaml
  ignore_errors: yes
# - import_playbook: T1138.yaml
#  ignore_errors: yes
#- import_playbook: T1182.yaml
#  ignore_errors: yes

- name: Generate report
  hosts: windows
  tasks:
    - name: check if windows defender is activated
      tags: always
      win_shell: Get-MpPreference | findstr DisableRealtimeMonitoring
      register: WindowsDefender
    - name: debug
      tags: always
      debug: var=WindowsDefender
      debug: var=WindowsDefender.stdout
    - name: debug msg for windows defender turn on
      tags: always
      debug: msg="Playbook ran#PRIV-ESCALATION-WIN-DEFENDER#"
      when: "'False' in WindowsDefender.stdout"
    - name: debug msg for defense turn off
      tags: always
      debug: msg="Playbook ran#PRIV-ESCALATION-NO-AV-EDR#"
      when: "'True' in WindowsDefender.stdout"
    - name: Generate report
      tags: always
      command: python3 /opt/ansible/report.py
      delegate_to: localhost
