# attack_technique: T1103
- name: T1103 - AppInit DLLs
  hosts: windows
  vars_files:
   - /opt/ansible/vars.yaml
  tasks:
    - name: copy cnc.dll
      tags: always
      win_copy:
        src: /opt/ansible/files/cnc.dll
        dest: c:\temp\
    - name: copy T1103.reg
      tags: always
      win_copy:
        src: /opt/ansible/files/T1103.reg
        dest: c:\temp\
    - name: copy T1103-cleanup.reg
      tags: always
      win_copy:
        src: /opt/ansible/files/T1103-cleanup.reg
        dest: c:\temp\
    - name: Update registry key
      tags: always
      win_command: |
        reg.exe import c:\temp\T1103.reg
    - name: Check REG exist
      tags: always
      win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows\AppInit_DLLs
      register: T1103
    - debug: msg="{{ T1103.stdout }}"
      tags: always
    - name: sleep for 10 seconds and continue with play to check if AV removed or Not
      tags: always
      wait_for: timeout=10
      delegate_to: localhost
    - name: check if playbook was blocked
      tags: always
      debug: msg="Playbook Completed#T1103#blocked#win#"
      when: T1103.exists == False        
    - name: check if playbook was successfull
      tags: always
      debug: msg="Playbook Completed#T1103#passed#win#"
      when: T1103.exists 
 
    - name: Cleanup registry key
      tags: always
      win_command: |
        reg.exe import c:\temp\T1103-cleanup.reg
    - name: delete files
      tags: always
      win_file:
        path: "{{ item }}"
        state: absent
      with_items:
        - c:\temp\cnc.dll
        - c:\temp\T1103.reg
        - c:\temp\T1103-cleanup.reg
